site_name: Documentación Pachamama

theme:
  name: material
  palette:
    primary: green
    accent: light green

nav:
  - Inicio: index.md
  - Arquitectura MVP (Pre-Pro): MVP-ARCHITECTURE.md
  - Servicios:
      - Web Landing: services/pachamama-web-landing/README.md